package com.momentor.mentors.DTO;

public class TaskResponseDto {
    private Long id;
    private String title;
    private String assignedTo;
    private String status;
    private boolean autoGenerated;
    private boolean approved;
    private String resources;
    private String meetingType;

    public TaskResponseDto(Long id, String title, String assignedTo,
                           String status, boolean autoGenerated,
                           boolean approved,String resources,String meetingType) {
        this.id = id;
        this.title = title;
        this.assignedTo = assignedTo;
        this.status = status;
        this.autoGenerated = autoGenerated;
        this.approved = approved;
        this.resources=resources;
        this.meetingType=meetingType;
    }

    public Long getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getAssignedTo() {
        return assignedTo;
    }

    public String getStatus() {
        return status;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public boolean isApproved() {
        return approved;
    }

    public String getResources() {
        return resources;
    }

    public String getMeetingType() {
        return meetingType;
    }
}
