package com.momentor.mentors.entity;

import jakarta.persistence.*;

import java.time.LocalDateTime;

@Entity
public class Task {
    public static final String CANCELLED = "CANCELLED";
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Long id;
    private String title;
    private String assignedTo;
    private String status;
    private LocalDateTime createdat;
    private boolean autoGenerated; //Ai Or Manual
    private boolean approved; //After Creation Of Task Mentor Approval
    @Column(columnDefinition="TEXT")
    private String resources;
    @ManyToOne
    @JoinColumn(name="mom_id")
    private Moms  mom;
    private String priority;
    private LocalDateTime dueDate;
    private boolean aiSuggestedDeadline;
    private boolean remindersent=false;
    public Task(){
        this.createdat=LocalDateTime.now();
        this.status="NOT_STARTED";
        this.priority="MEDIUM";
    }
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }
    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status;
    }
    public LocalDateTime getCreatedat() {
        return createdat;
    }
    public void setCreatedat(LocalDateTime createdat) {
        this.createdat = createdat;
    }
    public Moms getMom() {
        return mom;
    }
    public void setMom(Moms mom) {
        this.mom = mom;
    }
    public String getAssignedTo() {
        return assignedTo;
    }
    public void setAssignedTo(String assignedTo) {
        this.assignedTo = assignedTo;
    }
    public boolean isAutoGenerated() {
        return autoGenerated;
    }
    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }
    public boolean isApproved() {
        return approved;
    }
    public void setApproved(boolean approved) {
        this.approved = approved;
    }
    public String getResources() {
        return resources;
    }

    public void setResources(String resources) {
        this.resources = resources;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public LocalDateTime getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDateTime dueDate) {
        this.dueDate = dueDate;
    }

    public boolean isAiSuggestedDeadline() {
        return aiSuggestedDeadline;
    }

    public void setAiSuggestedDeadline(boolean aiSuggestedDeadline) {
        this.aiSuggestedDeadline = aiSuggestedDeadline;
    }

    public boolean isRemindersent() {
        return remindersent;
    }

    public void setRemindersent(boolean remindersent) {
        this.remindersent = remindersent;
    }
}
